name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_core: 1.3.0
  firebase_auth: 2.0.0
  cloud_firestore: 2.3.0
  firebase_storage: 9.0.0
  google_sign_in: 5.0.4
  introduction_screen: 2.1.0
  avatar_glow: 2.0.1
  emoji_picker_flutter: 1.0.6
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.3+2

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

